name: blender340
channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.10.8
  - numpy
  - pandas
  - pip:
    - bpy==3.4.0
    - ipykernel==6.15.3
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jupyter==1.0.0
    - jupyter-client==7.3.5
    - jupyter-console==6.4.4
    - jupyter-core==4.11.1
    - matplotlib==3.6.0
    - matplotlib-inline==0.1.6
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - seaborn==0.12.1
    - tqdm==4.64.1
    - vtk==9.1.0